name: "warlock-compose-fs"
services:
  warlock-ai-service:
    build: "../."
    container_name: "warlock-ai-container"
    restart: "unless-stopped"
    ports:
      - "8125:8123"
    env_file:
      - "../.env"
      - "./app/.env"
    networks:
      - "warlock-network"
    depends_on:
      - "warlock-llm-service"
      - "warlock-db-service"
    volumes:
      - shared-filestore:/app/filestore
  warlock-llm-service:
    image: "ollama/ollama:latest"
    container_name: "warlock-llm-container"
    restart: "unless-stopped"
    ports:
      - "11125:11434"
    env_file:
      - "./llm/.env"
    networks:
      - "warlock-network"
    volumes:
      - "warlock-llm-volume:/root/.ollama"
      - "./llm/entrypoint.sh:/entrypoint.sh"
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
  warlock-db-service:
    image: "pgvector/pgvector:pg16"
    container_name: "warlock-db-container"
    restart: "unless-stopped"
    ports:
      - "5125:5432"
    env_file:
      - "./db/.env"
    networks:
      - "warlock-network"
    volumes:
      - "warlock-db-volume:/data/postgres"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
  warlock-llm-volume:
  warlock-db-volume:
  shared-filestore:
    name: shared-filestore
    driver: local

networks:
  warlock-network:
    external: false
